name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    name: Build, Vet, Lint, Test (${{ matrix.os }}, Go ${{ matrix.go }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ["1.22.x", "1.23.x"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Go env
        run: |
          go env

      - name: Build (CGO disabled for headless build)
        env:
          CGO_ENABLED: 0
        run: |
          go build ./...

      - name: go vet
        run: |
          go vet ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m

      - name: Test (race)
        env:
          CGO_ENABLED: 0
        run: |
          go test -race ./...

      # Optional benchmarks (disabled by default). Enable with workflow_dispatch input or env in future.
      # - name: Benchmarks
      #   if: ${{ false }}
      #   run: |
      #     go test -bench=. -run=^$ ./...

